import os
import tempfile
from datetime import datetime

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from fpdf import FPDF

# =========================================================
# FONT PATHS
# =========================================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.join(BASE_DIR, "fonts")
FONT_REGULAR = os.path.join(FONT_DIR, "DejaVuSans.ttf")
FONT_BOLD = os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")
FONT_ITALIC = os.path.join(FONT_DIR, "DejaVuSans-Oblique.ttf")
FONT_NAME = "DejaVu"

# =========================================================
# PDF CLASS
# =========================================================
class FinSightPDF(FPDF):

    def __init__(self):
        super().__init__()
        self.add_font(FONT_NAME, "", FONT_REGULAR)
        self.add_font(FONT_NAME, "B", FONT_BOLD)
        self.add_font(FONT_NAME, "I", FONT_ITALIC)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_fill_color(102, 126, 234)
        self.rect(0, 0, 210, 18, "F")
        self.set_font(FONT_NAME, "B", 13)
        self.set_text_color(255, 255, 255)
        self.set_y(4)
        self.cell(0, 10, "FinSight — AI Financial Advisor Report", align="C")
        self.set_text_color(0, 0, 0)
        self.ln(16)

    def footer(self):
        self.set_y(-12)
        self.set_font(FONT_NAME, "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(
            0, 10,
            f"Generated by FinSight | "
            f"{datetime.now().strftime('%d %B %Y %I:%M %p')} | "
            f"Page {self.page_no()}",
            align="C"
        )

# =========================================================
# HELPERS
# =========================================================
def save_chart_as_image(fig, path):
    try:
        pio.write_image(fig, path, width=700, height=380, scale=2)
        return True
    except Exception as e:
        print("Chart export error:", e)
        return False

def section_title(pdf, text):
    """Purple section header bar"""
    pdf.set_fill_color(102, 126, 234)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font(FONT_NAME, "B", 11)
    pdf.cell(0, 8, f"  {text}", fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(10)

# =========================================================
# MAIN PDF FUNCTION
# =========================================================
def generate_pdf_report(kpis, cp, forecast, warnings, tips):

    pdf = FinSightPDF()
    tmp_dir = tempfile.mkdtemp()

    def font(style="", size=10):
        pdf.set_font(FONT_NAME, style, size)

    # =====================================================
    # PAGE 1 — OVERVIEW + KPI CARDS
    # =====================================================
    pdf.add_page()

    font("I", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6,
             f"Report generated: {datetime.now().strftime('%d %B %Y')}",
             align="R")
    pdf.ln(8)

    section_title(pdf, "FINANCIAL OVERVIEW")

    # KPI Cards
    kpi_items = [
        ("Total Revenue",
         f"Rs {kpis['total_revenue']:,.0f}", (0, 204, 150)),
        ("Total Expenses",
         f"Rs {kpis['total_expenses']:,.0f}", (239, 85, 59)),
        ("Net Profit",
         f"Rs {kpis['net_profit']:,.0f}", (102, 126, 234)),
        ("Profit Margin",
         f"{kpis['avg_profit_margin']}%", (255, 165, 0)),
        ("Cash Runway",
         f"{kpis['cash_runway_days']} days", (0, 188, 212)),
        ("Avg Growth",
         f"{kpis['avg_growth']}%", (118, 75, 162)),
    ]

    box_w = 60
    box_h = 22
    margin = 14
    per_row = 3
    start_y = pdf.get_y()

    for idx, (label, value, color) in enumerate(kpi_items):
        row = idx // per_row
        col = idx % per_row
        x = margin + col * (box_w + 5)
        y = start_y + row * (box_h + 4)

        pdf.set_fill_color(245, 247, 255)
        pdf.set_draw_color(*color)
        pdf.rect(x, y, box_w, box_h, "FD")
        pdf.set_fill_color(*color)
        pdf.rect(x, y, box_w, 3, "F")
        pdf.set_xy(x + 2, y + 5)
        font("", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(box_w - 4, 5, label)
        pdf.set_xy(x + 2, y + 11)
        font("B", 11)
        pdf.set_text_color(*color)
        pdf.cell(box_w - 4, 6, value)

    pdf.set_y(start_y + (box_h + 4) * 2 + 8)

    # Best / Worst month
    pdf.set_text_color(0, 0, 0)
    font("B", 10)
    pdf.set_fill_color(212, 237, 218)
    pdf.cell(90, 8,
             f"  Best Month: {kpis['best_month']}",
             fill=True)
    pdf.set_fill_color(248, 215, 218)
    pdf.cell(90, 8,
             f"  Worst Month: {kpis['worst_month']}",
             fill=True)
    pdf.ln(12)

    # Revenue vs Expenses chart
    section_title(pdf, "REVENUE VS EXPENSES")
    fig1 = px.bar(
        kpis["monthly_data"], x="Month",
        y=["Total_Income", "Total_Expenses"],
        barmode="group",
        color_discrete_sequence=["#667eea", "#f093fb"],
        template="plotly_white"
    )
    fig1.update_layout(margin=dict(t=20, b=20, l=20, r=20),
                       legend_title="")
    chart1 = os.path.join(tmp_dir, "chart1.png")
    if save_chart_as_image(fig1, chart1):
        pdf.image(chart1, x=14, w=182)

    # =====================================================
    # PAGE 2 — NET PROFIT + PROFIT MARGIN + EXPENSE PIE
    # =====================================================
    pdf.add_page()

    # Net Profit Trend
    section_title(pdf, "NET PROFIT TREND")
    fig2 = px.line(
        kpis["monthly_data"], x="Month", y="Net_Profit",
        markers=True, color_discrete_sequence=["#667eea"],
        template="plotly_white"
    )
    fig2.add_hline(y=0, line_dash="dash", line_color="red",
                   annotation_text="Break Even")
    fig2.update_layout(margin=dict(t=20, b=20, l=20, r=20))
    chart2 = os.path.join(tmp_dir, "chart2.png")
    if save_chart_as_image(fig2, chart2):
        pdf.image(chart2, x=14, w=182)

    pdf.ln(5)

    # Profit Margin % by Month
    section_title(pdf, "PROFIT MARGIN % BY MONTH")
    fig_margin = px.bar(
        kpis["monthly_data"], x="Month", y="Profit_Margin_%",
        color="Profit_Margin_%",
        color_continuous_scale="RdYlGn",
        template="plotly_white"
    )
    fig_margin.add_hline(y=20, line_dash="dash",
                         line_color="orange",
                         annotation_text="Healthy (20%)")
    fig_margin.update_layout(margin=dict(t=20, b=20, l=20, r=20))
    chart_margin = os.path.join(tmp_dir, "margin.png")
    if save_chart_as_image(fig_margin, chart_margin):
        pdf.image(chart_margin, x=14, w=182)

    # =====================================================
    # PAGE 3 — EXPENSE BREAKDOWN
    # =====================================================
    pdf.add_page()

    section_title(pdf, "EXPENSE BREAKDOWN")
    exp_data = pd.DataFrame({
        "Category": list(kpis["expense_categories"].keys()),
        "Amount": list(kpis["expense_categories"].values())
    })
    fig3 = px.pie(
        exp_data, names="Category", values="Amount",
        hole=0.45,
        color_discrete_sequence=px.colors.qualitative.Pastel
    )
    fig3.update_layout(margin=dict(t=20, b=20, l=20, r=20))
    chart3 = os.path.join(tmp_dir, "chart3.png")
    if save_chart_as_image(fig3, chart3):
        pdf.image(chart3, x=34, w=142)

    pdf.ln(5)

    # Expense table
    section_title(pdf, "EXPENSE CATEGORY SUMMARY")
    font("B", 9)
    pdf.set_fill_color(102, 126, 234)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(["Category", "Total Spent", "% of Total"],
                    [70, 60, 60]):
        pdf.cell(w, 8, h, fill=True, border=1, align="C")
    pdf.ln()

    total_exp = kpis["total_expenses"]
    for i, (cat, val) in enumerate(
            kpis["expense_categories"].items()):
        bg = (245, 247, 255) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.set_text_color(50, 50, 50)
        font("", 9)
        pdf.cell(70, 7, f"  {cat}", fill=True, border=1)
        pdf.cell(60, 7, f"Rs {val:,.0f}",
                 fill=True, border=1, align="R")
        pct = (val / total_exp * 100) if total_exp > 0 else 0
        pdf.cell(60, 7, f"{pct:.1f}%",
                 fill=True, border=1, align="C")
        pdf.ln()

    # =====================================================
    # PAGE 4 — COMPANY POSITION + RADAR
    # =====================================================
    pdf.add_page()

    section_title(pdf, "COMPANY HEALTH & POSITION")

    # Position badge
    font("B", 14)
    pdf.set_text_color(102, 126, 234)
    pdf.cell(0, 10, f"Position: {cp['position']}", align="C")
    pdf.ln(8)

    # Score badge
    score_color = (
        (0, 204, 150) if cp["total_score"] >= 85
        else (102, 126, 234) if cp["total_score"] >= 70
        else (255, 165, 0) if cp["total_score"] >= 55
        else (239, 85, 59)
    )
    pdf.set_fill_color(*score_color)
    pdf.set_text_color(255, 255, 255)
    font("B", 12)
    pdf.cell(0, 10,
             f"Overall Score: {cp['total_score']} / 100",
             fill=True, align="C")
    pdf.ln(8)

    font("", 10)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(0, 6, cp["position_desc"])
    pdf.ln(6)

    # Score breakdown table
    section_title(pdf, "SCORE BREAKDOWN")
    font("B", 9)
    pdf.set_fill_color(102, 126, 234)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(["Category", "Score", "Value", "Status"],
                    [55, 30, 40, 65]):
        pdf.cell(w, 8, h, fill=True, border=1, align="C")
    pdf.ln()

    for i, (cat, data) in enumerate(cp["breakdown"].items()):
        bg = (245, 247, 255) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.set_text_color(50, 50, 50)
        font("", 9)
        pdf.cell(55, 7, f"  {cat}", fill=True, border=1)
        pdf.cell(30, 7, f"{data['score']}/{data['max']}",
                 fill=True, border=1, align="C")
        pdf.cell(40, 7, data["value"],
                 fill=True, border=1, align="C")
        pdf.cell(65, 7, data["status"],
                 fill=True, border=1, align="C")
        pdf.ln()

    pdf.ln(6)

    # Radar chart
    section_title(pdf, "COMPANY HEALTH RADAR")
    categories = list(cp["breakdown"].keys())
    scores = [cp["breakdown"][c]["score"] for c in categories]
    max_scores = [cp["breakdown"][c]["max"] for c in categories]
    pct_scores = [s/m*100 for s, m in zip(scores, max_scores)]

    fig_radar = go.Figure()
    fig_radar.add_trace(go.Scatterpolar(
        r=pct_scores + [pct_scores[0]],
        theta=categories + [categories[0]],
        fill="toself",
        fillcolor="rgba(102,126,234,0.2)",
        line=dict(color="#667eea", width=2),
        name="Your Company"
    ))
    fig_radar.add_trace(go.Scatterpolar(
        r=[100, 100, 100, 100, 100],
        theta=categories + [categories[0]],
        fill="toself",
        fillcolor="rgba(0,204,150,0.05)",
        line=dict(color="#00CC96", width=1, dash="dash"),
        name="Ideal"
    ))
    fig_radar.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 100])),
        showlegend=True,
        margin=dict(t=40, b=40, l=40, r=40)
    )
    chart_radar = os.path.join(tmp_dir, "radar.png")
    if save_chart_as_image(fig_radar, chart_radar):
        pdf.image(chart_radar, x=34, w=142)

    # =====================================================
    # PAGE 5 — ACTIONABLE INSIGHTS
    # =====================================================
    pdf.add_page()

    section_title(pdf, "ACTIONABLE BUSINESS INSIGHTS")

    impact_colors = {
        "Critical": (204, 0, 0),
        "High": (239, 85, 59),
        "Medium": (255, 165, 0),
        "Opportunity": (0, 204, 150)
    }

    for insight in cp["insights"]:
        color = impact_colors.get(insight["impact"],
                                  (100, 100, 100))

        # Area + impact badge
        pdf.set_fill_color(245, 247, 255)
        pdf.set_draw_color(*color)
        pdf.set_fill_color(*color)
        pdf.rect(14, pdf.get_y(), 3, 7, "F")
        pdf.set_xy(18, pdf.get_y())
        font("B", 10)
        pdf.set_text_color(*color)
        pdf.cell(140, 7, insight["area"])
        pdf.set_fill_color(*color)
        pdf.set_text_color(255, 255, 255)
        font("B", 8)
        pdf.cell(38, 7,
                 f"  {insight['impact']}",
                 fill=True, align="C")
        pdf.ln(8)

        # Problem
        pdf.set_x(14)
        font("", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(182, 5,
                       f"Problem: {insight['problem']}")

        # Action
        pdf.set_x(14)
        font("B", 9)
        pdf.set_text_color(0, 120, 0)
        pdf.multi_cell(182, 5,
                       f"Action: {insight['action']}")
        pdf.ln(5)

    pdf.ln(4)

    # Warnings
    section_title(pdf, "BUSINESS HEALTH WARNINGS")
    font("", 10)
    for w in warnings:
        pdf.set_fill_color(255, 243, 205)
        pdf.set_text_color(80, 60, 0)
        pdf.set_x(14)
        pdf.set_fill_color(255, 193, 7)
        pdf.rect(14, pdf.get_y(), 3, 8, "F")
        pdf.set_x(18)
        pdf.cell(0, 8, w)
        pdf.ln(10)

    pdf.ln(2)

    # Recommendations
    section_title(pdf, "RECOMMENDATIONS")
    font("", 10)
    for t in tips:
        pdf.set_text_color(0, 60, 80)
        pdf.set_fill_color(23, 162, 184)
        pdf.rect(14, pdf.get_y(), 3, 8, "F")
        pdf.set_x(18)
        pdf.cell(0, 8, t)
        pdf.ln(10)

    # =====================================================
    # PAGE 6 — REVENUE FORECAST
    # =====================================================
    if forecast:
        pdf.add_page()

        section_title(pdf, "3-MONTH REVENUE FORECAST")

        preds = forecast["predictions"]

        # Forecast KPI cards
        forecast_items = [
            ("Month 1 Forecast",
             f"Rs {preds[0]:,.0f}", (102, 126, 234)),
            ("Month 2 Forecast",
             f"Rs {preds[1]:,.0f}", (118, 75, 162)),
            ("Month 3 Forecast",
             f"Rs {preds[2]:,.0f}", (0, 204, 150)),
        ]

        card_start = pdf.get_y()
        for idx, (label, value, color) in enumerate(
                forecast_items):
            x = 14 + idx * 62
            y = card_start

            pdf.set_fill_color(245, 247, 255)
            pdf.set_draw_color(*color)
            pdf.rect(x, y, 58, 20, "FD")
            pdf.set_fill_color(*color)
            pdf.rect(x, y, 58, 3, "F")
            pdf.set_xy(x + 2, y + 5)
            font("", 8)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(54, 4, label)
            pdf.set_xy(x + 2, y + 11)
            font("B", 10)
            pdf.set_text_color(*color)
            pdf.cell(54, 5, value)

        pdf.set_y(card_start + 28)

        # Trend
        trend_color = (0, 150, 0) if "Growing" in forecast["trend"] \
                      else (200, 0, 0)
        pdf.set_fill_color(*trend_color)
        pdf.set_text_color(255, 255, 255)
        font("B", 10)
        pdf.cell(0, 8,
                 f"  Overall Trend: {forecast['trend']}  |  "
                 f"Avg Forecast: Rs {forecast['avg_forecast']:,.0f}",
                 fill=True)
        pdf.ln(10)

        # Forecast chart
        section_title(pdf, "ACTUAL VS FORECASTED REVENUE")
        fig_fc = px.bar(
            forecast["combined_df"],
            x="Month", y="Forecasted_Revenue",
            color="Type",
            color_discrete_map={
                "Actual": "#667eea",
                "Forecast": "#f093fb"
            },
            template="plotly_white"
        )
        fig_fc.update_layout(
            margin=dict(t=20, b=20, l=20, r=20),
            legend_title=""
        )
        chart_fc = os.path.join(tmp_dir, "forecast.png")
        if save_chart_as_image(fig_fc, chart_fc):
            pdf.image(chart_fc, x=14, w=182)

    # =====================================================
    # PAGE 7 — FULL P&L TABLE
    # =====================================================
    pdf.add_page()

    section_title(pdf, "PROFIT & LOSS STATEMENT")

    headers = ["Month", "Total Income",
               "Total Expenses", "Net Profit", "Margin %"]
    widths = [30, 40, 42, 38, 28]

    # Header
    font("B", 9)
    pdf.set_fill_color(102, 126, 234)
    pdf.set_text_color(255, 255, 255)
    for h, w in zip(headers, widths):
        pdf.cell(w, 8, h, fill=True, border=1, align="C")
    pdf.ln()

    # Rows
    for i, row in kpis["monthly_data"].iterrows():
        bg = (245, 247, 255) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        font("", 9)

        pdf.set_text_color(50, 50, 50)
        pdf.cell(widths[0], 7, str(row["Month"]),
                 fill=True, border=1)
        pdf.cell(widths[1], 7,
                 f"Rs {row['Total_Income']:,.0f}",
                 fill=True, border=1, align="R")
        pdf.cell(widths[2], 7,
                 f"Rs {row['Total_Expenses']:,.0f}",
                 fill=True, border=1, align="R")

        profit_color = (0, 150, 0) \
            if row["Net_Profit"] >= 0 else (200, 0, 0)
        pdf.set_text_color(*profit_color)
        pdf.cell(widths[3], 7,
                 f"Rs {row['Net_Profit']:,.0f}",
                 fill=True, border=1, align="R")

        pdf.set_text_color(50, 50, 50)
        pdf.cell(widths[4], 7,
                 f"{row['Profit_Margin_%']}%",
                 fill=True, border=1, align="C")
        pdf.ln()

    # Totals row
    pdf.set_fill_color(30, 39, 97)
    pdf.set_text_color(255, 255, 255)
    font("B", 9)
    pdf.cell(widths[0], 8, "TOTAL", fill=True, border=1)
    pdf.cell(widths[1], 8,
             f"Rs {kpis['monthly_data']['Total_Income'].sum():,.0f}",
             fill=True, border=1, align="R")
    pdf.cell(widths[2], 8,
             f"Rs {kpis['monthly_data']['Total_Expenses'].sum():,.0f}",
             fill=True, border=1, align="R")

    total_profit = kpis['monthly_data']['Net_Profit'].sum()
    tp_color = (0, 220, 120) if total_profit >= 0 \
               else (255, 100, 100)
    pdf.set_text_color(*tp_color)
    pdf.cell(widths[3], 8,
             f"Rs {total_profit:,.0f}",
             fill=True, border=1, align="R")
    pdf.set_text_color(255, 255, 255)
    pdf.cell(widths[4], 8,
             f"{kpis['avg_profit_margin']}%",
             fill=True, border=1, align="C")
    pdf.ln()

    # =====================================================
    # OUTPUT
    # =====================================================
    pdf_output = pdf.output(dest="S")
    pdf_bytes = (pdf_output.encode("latin1")
                 if isinstance(pdf_output, str)
                 else bytes(pdf_output))

    for f in os.listdir(tmp_dir):
        try:
            os.remove(os.path.join(tmp_dir, f))
        except:
            pass

    return pdf_bytes